[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd webapp/backend && PYTHONPATH=/app/webapp/backend python -m uvicorn integrated_main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[environments.production]
PORT = "8000"
ENVIRONMENT = "production"
PYTHON_VERSION = "3.11"
PYTHONPATH = "/app/webapp/backend"
