[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd webapp/backend && PYTHONPATH=/app/webapp/backend python -m uvicorn integrated_main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"

[environments.production]
PORT = "8000"
ENVIRONMENT = "production"
PYTHON_VERSION = "3.11"
PYTHONPATH = "/app/webapp/backend"

# Alternative gunicorn command for fallback
# startCommand = "cd webapp/backend && PYTHONPATH=/app/webapp/backend gunicorn integrated_main:app -w 2 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT --timeout 120 --access-logfile - --error-logfile -"
