[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd webapp/backend && python integrated_main.py --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[environments.production]
PORT = "8000"
ENVIRONMENT = "production"
PYTHON_VERSION = "3.11"
